// @ts-nocheck
import * as __fd_glob_68 from "../content/docs/pro/setup.mdx?collection=docs"
import * as __fd_glob_67 from "../content/docs/pro/pricing.mdx?collection=docs"
import * as __fd_glob_66 from "../content/docs/pro/backend.mdx?collection=docs"
import * as __fd_glob_65 from "../content/docs/tools/webfetch.mdx?collection=docs"
import * as __fd_glob_64 from "../content/docs/tools/tree.mdx?collection=docs"
import * as __fd_glob_63 from "../content/docs/tools/sql.mdx?collection=docs"
import * as __fd_glob_62 from "../content/docs/tools/savings.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/tools/read.mdx?collection=docs"
import * as __fd_glob_60 from "../content/docs/tools/pr.mdx?collection=docs"
import * as __fd_glob_59 from "../content/docs/tools/orient.mdx?collection=docs"
import * as __fd_glob_58 from "../content/docs/tools/multi-edit.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/tools/logs.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/tools/issue.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/tools/http.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/tools/grep.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/tools/glob.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/tools/github.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/tools/genome.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/tools/genome-status.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/tools/genome-propose.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/tools/genome-consolidate.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/tools/edit.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/tools/diff.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/tools/diff-semantic.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/tools/bash.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/tools/bash-tail.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/tools/bash-stop.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/tools/bash-start.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/tools/bash-list.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/tools/ask.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/skills/usage.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/skills/update.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/skills/tour.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/skills/status.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/skills/settings.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/skills/savings.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/skills/recall.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/skills/ollama-setup.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/skills/legend.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/skills/handoff.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/skills/genome-loop.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/skills/genome-init.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/skills/errors.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/skills/doctor.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/skills/demo.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/skills/dashboard.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/skills/coach.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/skills/benchmark.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/skills/badge.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/skills/allow.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/getting-started/quickstart.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/getting-started/permissions.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/getting-started/install.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/getting-started/index.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/concepts/status-line.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/concepts/stats-schema.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/concepts/genome.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/concepts/confidence-badges.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/concepts/animation.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/contributing/testing.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/contributing/releases.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/contributing/architecture.mdx?collection=docs"
import { default as __fd_glob_6 } from "../content/docs/tools/meta.json?collection=docs"
import { default as __fd_glob_5 } from "../content/docs/skills/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../content/docs/pro/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/getting-started/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/contributing/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/concepts/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "concepts/meta.json": __fd_glob_1, "contributing/meta.json": __fd_glob_2, "getting-started/meta.json": __fd_glob_3, "pro/meta.json": __fd_glob_4, "skills/meta.json": __fd_glob_5, "tools/meta.json": __fd_glob_6, }, {"contributing/architecture.mdx": __fd_glob_7, "contributing/releases.mdx": __fd_glob_8, "contributing/testing.mdx": __fd_glob_9, "concepts/animation.mdx": __fd_glob_10, "concepts/confidence-badges.mdx": __fd_glob_11, "concepts/genome.mdx": __fd_glob_12, "concepts/stats-schema.mdx": __fd_glob_13, "concepts/status-line.mdx": __fd_glob_14, "getting-started/index.mdx": __fd_glob_15, "getting-started/install.mdx": __fd_glob_16, "getting-started/permissions.mdx": __fd_glob_17, "getting-started/quickstart.mdx": __fd_glob_18, "skills/allow.mdx": __fd_glob_19, "skills/badge.mdx": __fd_glob_20, "skills/benchmark.mdx": __fd_glob_21, "skills/coach.mdx": __fd_glob_22, "skills/dashboard.mdx": __fd_glob_23, "skills/demo.mdx": __fd_glob_24, "skills/doctor.mdx": __fd_glob_25, "skills/errors.mdx": __fd_glob_26, "skills/genome-init.mdx": __fd_glob_27, "skills/genome-loop.mdx": __fd_glob_28, "skills/handoff.mdx": __fd_glob_29, "skills/legend.mdx": __fd_glob_30, "skills/ollama-setup.mdx": __fd_glob_31, "skills/recall.mdx": __fd_glob_32, "skills/savings.mdx": __fd_glob_33, "skills/settings.mdx": __fd_glob_34, "skills/status.mdx": __fd_glob_35, "skills/tour.mdx": __fd_glob_36, "skills/update.mdx": __fd_glob_37, "skills/usage.mdx": __fd_glob_38, "tools/ask.mdx": __fd_glob_39, "tools/bash-list.mdx": __fd_glob_40, "tools/bash-start.mdx": __fd_glob_41, "tools/bash-stop.mdx": __fd_glob_42, "tools/bash-tail.mdx": __fd_glob_43, "tools/bash.mdx": __fd_glob_44, "tools/diff-semantic.mdx": __fd_glob_45, "tools/diff.mdx": __fd_glob_46, "tools/edit.mdx": __fd_glob_47, "tools/genome-consolidate.mdx": __fd_glob_48, "tools/genome-propose.mdx": __fd_glob_49, "tools/genome-status.mdx": __fd_glob_50, "tools/genome.mdx": __fd_glob_51, "tools/github.mdx": __fd_glob_52, "tools/glob.mdx": __fd_glob_53, "tools/grep.mdx": __fd_glob_54, "tools/http.mdx": __fd_glob_55, "tools/issue.mdx": __fd_glob_56, "tools/logs.mdx": __fd_glob_57, "tools/multi-edit.mdx": __fd_glob_58, "tools/orient.mdx": __fd_glob_59, "tools/pr.mdx": __fd_glob_60, "tools/read.mdx": __fd_glob_61, "tools/savings.mdx": __fd_glob_62, "tools/sql.mdx": __fd_glob_63, "tools/tree.mdx": __fd_glob_64, "tools/webfetch.mdx": __fd_glob_65, "pro/backend.mdx": __fd_glob_66, "pro/pricing.mdx": __fd_glob_67, "pro/setup.mdx": __fd_glob_68, });